apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
  labels:
    name: grafana
spec:
  selector:
    app: grafana-server
  type: NodePort
  externalIPs: [35.174.62.204] # replace with your Worker node IP
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000