apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
  labels:
    name: prometheus
spec:
  selector:
    app: prometheus-server
  type: NodePort
  externalIPs: [35.174.62.204] # replace with your Worker node IP
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090