{
 "title": "Synthetic Transactions airpa.io",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "airpa.io Availability",
   "type": "gauge",
   "description": "UP/DOWN status of airpa.io",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "synthetic_time_to_landing_page" }
   ]
  },
  {
   "title": "Time to Landing Page",
   "type": "graph",
   "description": "Duration of time to navigate to https://airpa.io/login with a fresh instance of a Chrome browser.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "synthetic_time_to_landing_page" }
   ]
  },
  {
   "title": "Login Time",
   "type": "graph",
   "description": "Duration of time for logging in to airpa.io",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "synthetic_time_to_login" }
   ]
  },
  {
   "title": "Logout Time",
   "type": "graph",
   "description": "Duration of time it takes to logout of airpa.io",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "synthetic_time_to_logout" }
   ]
  }
 ]
}