apiVersion: apps/v1
kind: Deployment
metadata:
  name: synthetic-airpa-deployment
  namespace: monitoring
  labels:
    app: synthetic-airpa-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synthetic-airpa-exporter
  template:
    metadata:
      labels:
        app: synthetic-airpa-exporter
    spec:
      containers:
        - name: prometheus-synthetic-airpa
          image: .dkr.ecr.us-east-1.amazonaws.com/airpa/prometheus-synthetic-airpa:latest
          ports:
            - containerPort: 9901
---
apiVersion: v1
kind: Service
metadata:
  name: synthetic-airpa-service
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'false'
      prometheus.io/port:   '9901'
spec:
  selector:
    app: synthetic-airpa-exporter
  type: NodePort
  externalIPs: [35.174.62.204] # replace with your Worker node IP
  ports:
    - port: 9901
      targetPort: 9901
      nodePort: 31901